name: Rust 1.89.0 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-1-89-0:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust 1.89.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.89.0'
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Run clippy (linter)
        run: cargo clippy --all -- -D warnings

      - name: Run fmt (format check)
        run: cargo fmt --all -- --check
