name: Rust Nightly CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-nightly:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow nightly builds to fail without failing the entire workflow

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Run clippy (linter)
        run: cargo clippy --all -- -D warnings

      - name: Run fmt (format check)
        run: cargo fmt --all -- --check
